from typing import Iterable, Protocol
from uuid import UUID

from app.domain.entities.model_artifact import ModelArtifact


class IModelRepository(Protocol):
    def add(self, m: ModelArtifact) -> None: 
        ...
    def get(self, model_id: UUID) -> ModelArtifact | None: 
        ...
    def get_for_user(self, model_id: UUID, user_id: str) -> ModelArtifact | None:
        ...
    def update(self, m: ModelArtifact) -> None:
        ...
    def delete(self, model_id: UUID) -> ModelArtifact | None:
        ...
    def delete_for_user(self, model_id: UUID, user_id: str) -> ModelArtifact | None:
        ...
    def list_for_dataset(self, dataset_id: UUID) -> Iterable[ModelArtifact]:
        ...
    def list_for_dataset_for_user(
        self,
        dataset_id: UUID,
        user_id: str,
    ) -> Iterable[ModelArtifact]:
        ...
    def list(self, limit: int = 50) -> Iterable[ModelArtifact]: 
        ...
    def list_for_user(self, user_id: str, limit: int = 50) -> Iterable[ModelArtifact]:
        ...
    def sum_size_for_user(self, user_id: str) -> int:
        ...
